### ISSUE TITLE
db rejectUnauthorized should say true?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-node-modules#11]
![image](https://user-images.githubusercontent.com/6306961/94116902-1eb62300-fe3b-11ea-84f3-0a72201f8f3e.png)

This is harder to test - you would need to change this locally, then rebuild flowcrypt-node-modules, then rebuild other repo like flowcrypt-attester-ts, and test if you can still connect to a database with certificates enabled.

**Comment by tomholub** [comment]
@seisvelas added you to the repo in invitations - could not assign you until accepted. Thanks!

**Comment by seisvelas** [comment]
As far as I can tell this should be set to `true`. `rejectUnauthorized` means that the certificate should be checked against the CA you give it, so this should probably be set to true. From the docs:

>rejectUnauthorized <boolean> If not false the server will reject any connection which is not authorized with the list of supplied CAs.

\- https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

`true` appears to be the default anyway, which makes me wonder, was there a problem with the default that caused us to switch this to `false` in the first place?

In any case, I went ahead and tested this with flowcrypt-attester-ts. It breaks!

![Screenshot from 2020-09-24 20-48-38](https://user-images.githubusercontent.com/44826516/94220935-5b1f6880-fea7-11ea-8fdd-2061838b5741.png)

To fix it, I have to update `DB_HOST = '127.0.0.1';` in flowcrypt-node-modules/source/config.ts to say `DB_HOST = 'localhost';`

Rebuild and...now it works!

![Screenshot from 2020-09-24 20-51-09](https://user-images.githubusercontent.com/44826516/94221323-18aa5b80-fea8-11ea-93c4-b8edaaa3bb26.png)

Should I make a PR to change both? I'm not sure if something else out there depends on it saying `DB_HOST = '127.0.0.1';` and *not* `localhost`. Let me know your thoughts!
